metasearch/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
]

website/urls.py
from django.urls import path

from website.views import HomeView, SearchView, AboutView, register_request, login_request, logout_request,\
    OfferDetailsView

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('search', SearchView.as_view(), name='search'),
    path('about', AboutView.as_view(), name='about'),
    path("register", register_request, name="register"),
    path("login", login_request, name="login"),
    path("logout", logout_request, name="logout"),
    path("offer/<int:pk>", OfferDetailsView.as_view(), name="offer-details"),
]

scrappers/models.py
from django.db import models

# Create your models here.

website/models.py
from datetime import datetime

from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone
from model_utils import Choices


class OfferWebsite(models.Model):
    name = models.CharField(verbose_name='Strona', max_length=128)

    def __str__(self):
        return "{}".format(self.name)


class OfferCity(models.Model):
    name = models.CharField(verbose_name='Miasto', max_length=128)

    def __str__(self):
        return "{}".format(self.name)


class OfferPhoto(models.Model):
    photo = models.ImageField()


class Offer(models.Model):
    TYPES = Choices(
        (1, 'house', 'Dom'),
        (2, 'flat', 'Mieszkanie'),
        (3, 'rent', 'Wynajem'),
        (4, 'plot', 'Działka'),
    )
    title = models.CharField(verbose_name='Tytuł', max_length=255)
    city = models.ForeignKey(OfferCity, verbose_name='Miasto', on_delete=models.CASCADE)
    address = models.CharField(verbose_name='Adres', max_length=255)
    type = models.IntegerField(verbose_name='Rodzaj', choices=TYPES)
    website = models.ForeignKey(OfferWebsite, verbose_name='Strona', on_delete=models.CASCADE)
    area = models.DecimalField(verbose_name='Powierzchnia', decimal_places=2, max_digits=6,
                               validators=[MinValueValidator(1)])
    rooms = models.IntegerField(verbose_name='Ilość pokoi', validators=[MinValueValidator(1)])
    price = models.IntegerField(verbose_name='Cena', validators=[MinValueValidator(1)])
    created = models.DateTimeField(verbose_name='Utworzono', default=timezone.now)
    modified = models.DateTimeField(verbose_name='Ostatnia edycja', null=True, blank=True)
    photos = models.ManyToManyField(OfferPhoto, verbose_name="Zdjęcia")
    link = models.URLField(verbose_name='Link')

    @property
    def price_per_square_meter(self):
        return int(self.price / self.area)

    @property
    def details_url(self):
        return reverse_lazy('offer-details', kwargs={'pk': self.pk})

website/forms.py
from crispy_forms.helper import FormHelper
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from website.models import Offer


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].label = 'Nazwa użytkownika'
        self.fields['username'].help_text = 'Wymagane. 150 znaków lub mniej. Litery, liczby i @/./+/-/_ .'
        self.fields['password1'].label = 'Hasło'
        self.fields['password1'].help_text = '<ul> <li> Twoje hasło nie może być zbyt podobne do Twoich innych danych osobowych. </li> <li> Twoje hasło musi zawierać co najmniej 8 znaków. </li> <li> Twoje hasło nie może być powszechnie używane. </li> <li> Twoje hasło nie może składać się wyłącznie z cyfr. </li> </ul>'
        self.fields['password2'].label = 'Powtórz hasło'
        self.fields['password2'].help_text = 'Podaj to samo hasło dla weryfikacji.'

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class LoginUserForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].label = 'Nazwa użytkownika'
        self.fields['password'].label = 'Hasło'


class SearchForm(ModelForm):
    price_min = forms.IntegerField(min_value=0, required=False)
    price_max = forms.IntegerField(min_value=0, required=False)
    area_min = forms.IntegerField(min_value=0, required=False)
    area_max = forms.IntegerField(min_value=0, required=False)

    class Meta:
        model = Offer
        fields = ('type', 'website', 'area_min', 'area_max', 'rooms', 'price_min', 'price_max', 'city')

    def __init__(self, get=None, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_class = 'form-element row'
        self.helper.wrapper_class = 'col-md-2'
        self.helper.label_class = 'control-label'
        self.helper.field_class = 'control-form'

        self.fields['rooms'].required = False
        self.fields['website'].required = False

        city = get.get('city', None)
        if get.get('city', None):
            self.fields['city'].initial = city

        type = get.get('type', None)
        if get.get('type', None):
            self.fields['type'].initial = type
        else:
            self.fields['type'].initial = Offer.TYPES.flat

        website = get.get('site', None)
        if get.get('site', None):
            self.fields['website'].initial = website

scrappers/views.py
from django.shortcuts import render

# Create your views here.

website/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, FormView, DetailView

from scrappers.tasks import Search
from website.forms import NewUserForm, LoginUserForm, SearchForm
from website.models import Offer


class HomeView(TemplateView):
    template_name = 'home.html'


class AboutView(TemplateView):
    template_name = 'about.html'


class SearchView(FormView):
    template_name = 'search.html'
    form_class = SearchForm

    def get_form_kwargs(self):
        form_kwargs = super().get_form_kwargs()
        form_kwargs['get'] = self.request.GET
        return form_kwargs

    def form_valid(self, form):
        search = Search(form.cleaned_data)
        offers = search.search()

        context_data = self.get_context_data(form=form)
        context_data['offers'] = offers
        return self.render_to_response(context_data)


class OfferDetailsView(DetailView):
    template_name = 'offer.html'
    model = Offer
    queryset = Offer.objects.all()


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Rejestracja zakończona sukcesem.")
            return redirect("index")
        messages.error(request, "Rejestracja nie powiodła się. Złe dane.")
    form = NewUserForm
    return render(request=request, template_name="register.html", context={"register_form": form})


def login_request(request):
    if request.method == "POST":
        form = LoginUserForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"Zalogowano jako {username}.")
                return redirect("index")
            else:
                messages.error(request, "Zły login lub hasło.")
        else:
            messages.error(request, "Zły login lub hasło.")
    form = LoginUserForm()
    return render(request=request, template_name="login.html", context={"login_form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "Wylogowano.")
    return redirect("index")

templates/about.html
{% extends 'base.html' %}

{% load static %}

{% block body %}
<div class="bg-image-about">
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center">
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
        <div class="p-3 p-md-5 m-md-3 text-center">
            <div class="p-lg-5 mx-auto my-5 bg-semi-transparent">
                <p>
                Zaawansowana wyszukiwarka nieruchomości pozwala na znalezienie mieszkań oraz domów na wielu
                portalach na raz. Po podaniu parametrów wyszukiwania aplikacja wyśle zapytania do popularnych portali
                ogłoszeniowych z nieruchomościami i zwróci scalone wyniki.
                </p>
                <p>Dzięki temu możliwe jest porównanie
                wszystkich wyników i znalezienie najkorzystniejszej oferty.
                </p>
                <p>&nbsp</p>
                <p>
                    Strona stworzona przez Adrian Czok
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Adrian Czok">

    <title>{% block title %}Metasearch{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'assets/bootstrap/dist/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>

{% include 'navigation.html' %}

<body>
    {% block body %}
    <div class="p-3 p-md-5 m-md-3">
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
        <div class="p-lg-5 mx-auto my-5 bg-light">
            {% block content %}{% endblock %}
        </div>
    </div>
    {% endblock %}

    {% include 'footer.html' %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'assets/jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'assets/bootstrap/dist/js/bootstrap.js' %}"></script>
</body>
</html>

templates/footer.html
    <footer class="container py-5">
      <div class="row">
        <div class="col-4 col-md">
          <h5>Miasta</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="{% url 'search' %}?city=1">Warszawa</a></li>
            <li><a class="text-muted" href="{% url 'search' %}?city=2">Kraków</a></li>
            <li><a class="text-muted" href="{% url 'search' %}?city=3">Łódź</a></li>
            <li><a class="text-muted" href="{% url 'search' %}?city=4">Gdańsk</a></li>
            <li><a class="text-muted" href="{% url 'search' %}?city=5">Katowice</a></li>
            <li><a class="text-muted" href="{% url 'search' %}?city=6">Wrocław</a></li>
          </ul>
        </div>
        <div class="col-4 col-md">
          <h5>Nieruchomość</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="{% url 'search' %}?type=1">Dom</a></li>
            <li><a class="text-muted" href="{% url 'search' %}?type=2">Mieszkanie</a></li>
            <li><a class="text-muted" href="{% url 'search' %}?type=3">Wynajem</a></li>
            <li><a class="text-muted" href="{% url 'search' %}?type=4">Działki</a></li>
          </ul>
        </div>
        <div class="col-4 col-md">
          <h5>Strony</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="{% url 'search' %}?site=1">Otodom.pl</a></li>
            <li><a class="text-muted" href="{% url 'search' %}?site=2">Gratka.pl</a></li>
            <li><a class="text-muted" href="{% url 'search' %}?site=3">Domiporta.pl</a></li>
            <li><a class="text-muted" href="{% url 'search' %}?site=4">Olx.pl</a></li>
            <li><a class="text-muted" href="{% url 'search' %}?site=5">Nieruchomosci-online.pl</a></li>
          </ul>
        </div>
      </div>
    </footer>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block body %}
<div class="bg-image">
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center">
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
        <div class="col-md-5 p-lg-5 mx-auto my-5">
            <h1 class="display-4 font-weight-normal">Wyszukiwarka nieruchomości</h1>
            <p class="lead font-weight-normal">Wiele ofert w jednym miejscu. Znajdź swój wymarzony dom w najlepszej cenie.</p>
            <a class="btn btn-outline-danger" href="{% url 'search' %}">Zaczynamy!</a>
        </div>
    </div>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}      

{% load crispy_forms_tags %}

<!--Login-->
<div class="container">
    <h1>Logowanie</h1>
    <form method="POST">
        {% csrf_token %}
        {{ login_form|crispy }}
        <button class="btn btn-primary mt-2" type="submit">Zaloguj się</button>
    </form>
    <p class="text-center">Nie masz konta? <a href="{% url 'register' %}">Zarejestruj się</a>.</p>
</div>

{% endblock %}

templates/navigation.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">Start</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'search' %}">Wyszukiwarka</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">O nas</a>
            </li>
        </ul>
        <div class="btn-group">
            <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'login' %}">Logowanie</a>
            <button type="button" class="btn btn-outline-success dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'logout' %}">Wyloguj się</a>
            </div>
        </div>
    </div>
</nav>

templates/offer.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="row">
        <div class="col-md-5">
            <div class="offer-info-box mt-0">
                <h5>{{ offer.get_type_display }}</h5>
                <p class="mb-0">{{ offer.title }}</p>
            </div><!-- / offer-info-box -->

            <div class="offer-info-box">
                <p><b>Miasto:</b> {{ offer.city }}</p>
                <p><b>Ilość pokoi:</b> {{ offer.rooms }}</p>
                <p><b>Powierzchnia:</b> {{ offer.area|floatformat:"0" }}</p>
                <p><b>Adres:</b> {{ offer.address }}</p>
                <p class="mb-0"><b>Cena:</b> {{ offer.price }} zł</p>
            </div><!-- / offer-info-box -->

            <div class="offer-info-box mt-0 mb-0">
                <p class="mb-0">
                    <span class="fw-bold mr-10 va-middle hide-mobile">Otwórz ogłoszenie w nowej karcie:</span>
                    <a href="{{ offer.link }}" class="btn btn-circle btn-primary float-right" target="_blank">Link</a>
                </p>
            </div><!-- / project-info-box -->
        </div><!-- / column -->

        <div class="col-md-7">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    {% for photo in offer.photos.all %}
                        <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter }}" class="{% if forloop.first %}active{% endif %}"></li>
                    {% empty %}
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    {% endfor %}
                </ol>
                <div class="carousel-inner">
                    {% for photo in offer.photos.all %}
                        <div class="carousel-item {% if forloop.first %}active{% endif %}">
                            <img class="d-block w-100" src="https://via.placeholder.com/400x200/FFB6C1/000000" alt="First slide">
                        </div>
                    {% empty %}
                        <div class="carousel-item active">
                            <img class="d-block w-100" src="https://via.placeholder.com/400x200/FFB6C1/000000" alt="First slide">
                        </div>
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <div class="offer-info-box">
                <p><b>Ze strony:</b> {{ offer.website }}</p>
                <p><b>Utworzono:</b> {{ offer.created }}</p>
                <p><b>Zmodyfikowano:</b> {{ offer.modified | default:'' }}</p>
            </div><!-- / offer-info-box -->
        </div><!-- / column -->
    </div>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block content %} 

{% load crispy_forms_tags %}

<!--Register-->
<div class="container">
    <h1>Rejestracja</h1>
    <form method="POST">
        {% csrf_token %}
        {{ register_form|crispy }}
        <button class="btn btn-primary mt-2" type="submit">Zarejestruj się</button>
    </form>
    <p class="text-center">Jeżeli masz już konto, <a href="{% url 'login' %}">zaloguj się</a>.</p>
</div>

{% endblock %}

templates/search.html
{% extends 'base.html' %}

{% load static crispy_forms_tags %}

{% block content %}
    <div class="text-center">
        <form method="post">
            {% csrf_token %}
            <div class="form-row">
                {{ form.type|as_crispy_field }}
                {{ form.city|as_crispy_field }}
                <div id="div_id_price" class="form-group col-lg-4">
                    <label for="id_price_min" class="control-label">
                        Cena</label>
                    <div class="row">
                        <div class="col">
                            <input value="{{ form.data.price_min }}" name="price_min" id="id_price_min" type="number" class="numberinput form-control" min="0" step="50000" placeholder="100000">
                        </div>
                        -
                        <div class="col">
                            <input value="{{ form.data.price_max }}" name="price_max" id="id_price_max" type="number" class="numberinput form-control" min="0" step="50000" placeholder="200000">
                        </div>
                    </div>
                </div>
                <div id="div_id_rooms" class="form-group col-lg-1">
                    <label for="id_rooms" class="control-label">
                        Pokoje</label>
                    <div class="control-form">
                        <input value="{{ form.data.rooms }}" type="number" name="rooms" placeholder="4" class="numberinput form-control" id="id_rooms">
                    </div>
                </div>
                <div id="div_id_area" class="form-group col-lg-2">
                    <label for="id_area_min" class="control-label">
                        Powierzchnia</label>
                    <div class="row">
                        <div class="col">
                            <input value="{{ form.data.area_min }}" name="area_min" id="id_area_min" type="number" class="numberinput form-control" placeholder="40">
                        </div>
                        -
                        <div class="col">
                            <input value="{{ form.data.area_max }}" name="area_max" id="id_area_max" type="number" class="numberinput form-control" placeholder="80">
                        </div>
                    </div>
                </div>
                {{ form.website|as_crispy_field }}
                <div id="div_id_submit" class="form-group col-lg-2">
                    <label for="submit" class="control-label">
                        <span class="asteriskField">&nbsp</span> </label>
                    <div class="control-form">
                        <button type="submit" class="btn btn-primary btn-block" id="submit">Szukaj</button>
                    </div>
                </div>
            </div>
        </form>
        {% if offers %}
            <table class="table mt-5">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Tytuł</th>
                    <th scope="col">Cena</th>
                    <th scope="col">Cena za m2</th>
                    <th scope="col">Powierzchnia</th>
                    <th scope="col">Miasto</th>
                </tr>
                </thead>
                <tbody>

                {% for offer in offers %}
                    <tr>
                        <th scope="row"><a href="{{ offer.details_url }}" target="_blank"><button class="btn {% if forloop.counter > 3 %}btn-success{% else %}btn-danger{% endif %} btn-block offer-btn">{{ forloop.counter }}</button></a></th>
                        <td>{{ offer.title }}</td>
                        <td>{{ offer.price }}</td>
                        <td>{{ offer.price_per_square_meter }}</td>
                        <td>{{ offer.area }}</td>
                        <td>{{ offer.city }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
{% endblock %}